---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/myapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/myapp:appimage
   ports:
     - "1222:80"
   depends_on:
     - "devopsdb"
